DROP DATABASE IF EXISTS employee_tracker;
CREATE DATABASE employee_tracker;

USE employee_tracker;

CREATE TABLE department (
 id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 name VARCHAR(30) NOT NULL,


CREATE TABLE role (
 id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 title VARCHAR(30) NOT NULL,
 salary DECIMAL NOT NULL,
 department_id INT  NOT NULL);
 
 CREATE TABLE employee (
 id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 first_name VARCHAR(30) NOT NULL,
 last_name VARCHAR(30) NOT NULL,
 role_id INT  NOT NULL,
 manager_id INT  NOT NULL)